In [7]:
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import csv
#import emoji #pip install emoji --upgrade
import re
%matplotlib inline

In [8]:
file1 = open('good_tweets_full.json','r')
good_full = file1.read().splitlines()

file2 = open('good_tweets_full_cn.json','r')
good_cn = file2.read().splitlines()

file3 = open('good_tweets_full_jp.json','r')
good_jp = file3.read().splitlines()

file4 = open('good_tweets_full_ml.json','r')
#good_ml = file4.read().splitlines()  don't need to split; threw errors

file5 = open('good_tweets_full_sp.json','r')
#good_sp = file5.read().splitlines()

In [9]:
# then edit this function to actually add the fields into a resulting dictionary

def get_fields(tweet_str):
    tweet_dict ={}
    tweet_json = json.loads(tweet_str)
    tweet_dict[col[0]] = tweet_json['text']
    tweet_dict[col[1]] = tweet_json['user']['name']
    tweet_dict[col[2]] = tweet_json['coordinates']
    tweet_dict[col[3]] = tweet_json['place']
    tweet_dict[col[4]] = tweet_json['user']['location']
    tweet_dict[col[5]] = tweet_json['lang']
    return tweet_dict

In [10]:
# Edit column names to include the fields that needs to be extracted.
col = ['text', 'screen_name', 'latLong','tweetLocation','userLocation',
       'tweetLang']

df_good = pd.DataFrame(columns=col)
for tweet in good_full:
    df_good = df_good.append(get_fields(tweet), ignore_index = True)

df_cn = pd.DataFrame(columns=col)
for tweet in good_cn:
    df_cn = df_cn.append(get_fields(tweet), ignore_index = True)

df_jp = pd.DataFrame(columns=col)
for tweet in good_jp:
    df_jp = df_jp.append(get_fields(tweet), ignore_index = True)

df_ml = pd.DataFrame(columns=col)
for tweet in file4:
    df_ml = df_ml.append(get_fields(tweet), ignore_index = True)   
    
df_sp = pd.DataFrame(columns=col)
for tweet in file5:
    df_sp = df_sp.append(get_fields(tweet), ignore_index = True)

In [11]:
print('good_full: ', df_good.shape)
print('good_sp: ', df_sp.shape)
print('good_cn: ', df_cn.shape)
print('good_ml: ', df_ml.shape)
print('good_jp: ', df_jp.shape)

good_full:  (8518, 6)
good_sp:  (416, 6)
good_cn:  (570, 6)
good_ml:  (348, 6)
good_jp:  (860, 6)

In [12]:
df_all = pd.concat([df_good, df_cn, df_jp, df_ml, df_sp])

In [13]:
df_all.shape

(10712, 6)

In [14]:
df_all.head()

,text,screen_name,latLong,tweetLocation,userLocation,tweetLang
0,RT @TWICEREPORT: 📷 | 181104 Atualização do sit...,vicks🌙,None,None,Vale da Viadagem,pt
1,@ABSTRAXT_DOMO I feel you man I really do 😩,Scorpioo ♏️💧,None,None,,en
2,"@BTS_twt EEE my beautiful flowers. :"")💜 i just...",KawaiiAsagao🐰🌈🌸🌻🌷🍀🍧🌞🦋🌺💫💐🍬🌼🍉❄️,None,None,Kawaiiland (◕‿◕✿) (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧,en
3,"@bestcryptoexc 🔹 Mighty Signals, Upto 23%-50% ...",Alisha,None,None,"Evansville, Indiana, USA",en
4,"@Tomm_Shelby 🔹 Powerful Signals, Upto 23%-50% ...",Laura,None,None,"Bellevue, Washington, USA",en

print(df_all.shape)
print(df_all.isnull().sum())

In [15]:
df_all['tweetLang'].value_counts()

en     6991
ja     1604
es      493
in      403
zh      219
ko      182
fr      175
pt      127
th      111
tl      106
und     101
ar       50
ca       20
hi       16
it       15
tr       14
ht       13
pl       12
de       12
ru        9
et        8
fi        5
ta        5
sv        3
nl        3
no        2
fa        2
cs        2
el        1
lt        1
hu        1
vi        1
eu        1
cy        1
ne        1
ro        1
da        1
Name: tweetLang, dtype: int64

In [10]:
df_all['userLocation'].value_counts()

                               941
日本                              31
Malaysia                        19
United States                   18
India                           14
ประเทศไทย                       11
California, USA                 10
Indonesia                        9
USA                              8
Japan                            7
日本 東京                            7
Tokyo, Japan                     7
Ikeja, Lagos                     6
東京                               6
Republic of the Philippines      6
Los Angeles, CA                  6
Seoul Korea                      6
Florida, USA                     6
Canada                           5
Tokyo                            5
New York, NY                     5
New Jersey, USA                  5
London, England                  4
México                           4
Texas, USA                       4
Charlotte, NC                    4
Seattle, WA                      4
Taiwan                           4
神奈川県                             4
في راس الجبل                     4
                              ...
ES                               1
Spokane, WA                      1
埼玉 川越市                           1
Universe.                        1
Ciudad Juárez, Chihuahua         1
paris                            1
México                           1
Somewhere enjoying myself ✨      1
Maryland US @WhoopiesMind        1
スルリ抜ける願い                         1
Manila Philippines               1
Sunset Park, Brooklyn            1
工地                               1
Hyderabad                        1
리더 해줘서 고마워                       1
Buscandome...                    1
San Isidro, Argentina            1
La Araucanía. 🇨🇱                 1
OSAKA                            1
404 • VState                     1
Bogor                            1
سلطنة عمان                       1
肋骨尊い                             1
お別れはブロックで※B解🙅                    1
Russia, OH                       1
George Town, Pinang              1
阪神甲子園球場ライトスタンド                   1
Rosario/San Nicolás              1
地雷自衛済｜FBRお気軽に                    1
キャンベル邸の地下室                       1
Name: userLocation, Length: 1390, dtype: int64

In [11]:
'''

#new from Anup


from geopy.geocoders import Nominatim
from geotext import GeoText
from geopy.extra.rate_limiter import RateLimiter

#data = []
#with open('result/good_tweets.json') as f:
#    for line in f:
#        data.append(json.loads(line))     

geolocator = Nominatim(country_bias="United States")

geocode = RateLimiter(geolocator.geocode, min_delay_seconds=5)

data_loc = []

for i,j in enumerate(data):
    places = GeoText(j['user']['location'])
#     if places.cities:
    if places.countries:
        location = geolocator.geocode(places.countries[0], exactly_one=True)
        try:
            address = location.address
            latitude = location.latitude
            longitude = location.longitude
            data_loc.append([address,latitude,longitude])
            print("index in good_tweets.json = {}, place name = {}, latitude = {}, longitude = {}:".format(i, address, latitude, longitude))
        except AttributeError:
            data_loc.append([None,None,None])
            print("Error, {} not found".format(str(places.cities)))
    else:
        data_loc.append([None,None,None])
        
#convert to dataframe
df_loc = pd.DataFrame(data_loc,columns=['address','latitude','longitude'])

'''

'\n\n#new from Anup\n\n\nfrom geopy.geocoders import Nominatim\nfrom geotext import GeoText\nfrom geopy.extra.rate_limiter import RateLimiter\n\n#data = []\n#with open(\'result/good_tweets.json\') as f:\n#    for line in f:\n#        data.append(json.loads(line))     \n\ngeolocator = Nominatim(country_bias="United States")\n\ngeocode = RateLimiter(geolocator.geocode, min_delay_seconds=5)\n\ndata_loc = []\n\nfor i,j in enumerate(data):\n    places = GeoText(j[\'user\'][\'location\'])\n#     if places.cities:\n    if places.countries:\n        location = geolocator.geocode(places.countries[0], exactly_one=True)\n        try:\n            address = location.address\n            latitude = location.latitude\n            longitude = location.longitude\n            data_loc.append([address,latitude,longitude])\n            print("index in good_tweets.json = {}, place name = {}, latitude = {}, longitude = {}:".format(i, address, latitude, longitude))\n        except AttributeError:\n            data_loc.append([None,None,None])\n            print("Error, {} not found".format(str(places.cities)))\n    else:\n        data_loc.append([None,None,None])\n        \n#convert to dataframe\ndf_loc = pd.DataFrame(data_loc,columns=[\'address\',\'latitude\',\'longitude\'])\n\n'

In [12]:
#KT edit Anup's

from geopy.geocoders import Nominatim
from geotext import GeoText
from geopy.extra.rate_limiter import RateLimiter

#data = []
#with open('result/good_tweets.json') as f:
#    for line in f:
#        data.append(json.loads(line))     

geolocator = Nominatim(country_bias="United States")

geocode = RateLimiter(geolocator.geocode, min_delay_seconds=5)



data_loc = []

for i, row in df_all.iterrows():
    places = GeoText(row['userLocation'])
#     if places.cities:
    if places.countries:
        location = geolocator.geocode(places.countries[0], exactly_one=True)
        try:
            address = location.address
            latitude = location.latitude
            longitude = location.longitude
            data_loc.append([address,latitude,longitude])
            #print("index in good_tweets.json = {}, place name = {}, latitude = {}, longitude = {}:".format(i, address, latitude, longitude))
        except AttributeError:
            data_loc.append([None,None,None])
            #print("Error, {} not found".format(str(places.cities)))
    else:
        data_loc.append([None,None,None])
        
#convert to dataframe
df_loc = pd.DataFrame(data_loc,columns=['address','latitude','longitude'])

/anaconda3/lib/python3.6/site-packages/geopy/geocoders/osm.py:143: UserWarning: Using Nominatim with the default "geopy/1.17.0" `user_agent` is strongly discouraged, as it violates Nominatim's ToS https://operations.osmfoundation.org/policies/nominatim/ and may possibly cause 403 and 429 HTTP errors. Please specify a custom `user_agent` with `Nominatim(user_agent="my-application")` or by overriding the default `user_agent`: `geopy.geocoders.options.default_user_agent = "my-application"`. In geopy 2.0 this will become an exception.
  UserWarning

In [13]:
df_loc.head(10)

  address  latitude  longitude
0    None       NaN        NaN
1    None       NaN        NaN
2    None       NaN        NaN
3    None       NaN        NaN
4    None       NaN        NaN
5    None       NaN        NaN
6    None       NaN        NaN
7    None       NaN        NaN
8    None       NaN        NaN
9    None       NaN        NaN

In [14]:
df_loc.isnull().sum()

address      2402
latitude     2402
longitude    2402
dtype: int64

In [15]:
df_allin = df_all.join(df_loc)

In [16]:
df_allin

,text,screen_name,latLong,tweetLocation,userLocation,tweetLang,address,latitude,longitude
0,RT @TWICEREPORT: 📷 | 181104 Atualização do sit...,vicks🌙,None,None,Vale da Viadagem,pt,None,NaN,NaN
0,RT @hinata831aimi: 「KiREI」初定期公演\nありがとうございました🎀🐾...,ひぃろ,None,None,,ja,None,NaN,NaN
0,RT @ponpu4649: @yuad127 にゃっほ～!! ハイハイ立っちができお手手開...,博多のマッサージは,None,None,福岡市博多区博多駅前4-15-10,ja,None,NaN,NaN
0,@SalmaBrecht @PKSejahtera 😀😀 @PKSejahtera N...,FiermanNrd,None,None,Bogor,in,None,NaN,NaN
0,@Leon_Malo @LhommedeJara @MichelBARRET1 😂 \nEn...,PoussiG ن,None,None,,fr,None,NaN,NaN
1,@ABSTRAXT_DOMO I feel you man I really do 😩,Scorpioo ♏️💧,None,None,,en,None,NaN,NaN
1,えっち写メみたいー？\n興味ありさんLINEして♥♥\nhttps://t.co/37nLi...,紗耶香,None,None,,ja,None,NaN,NaN
1,RT @inariya_fusa: ✨冬コミ当選しました～！\n12/29(土) 東地区 シ...,日本橋,None,None,,ja,None,NaN,NaN
1,@titikabur @srydntpride // aku lebih tinggi 9c...,Niklaus,None,None,"Jakarta Pusat, DKI Jakarta",in,None,NaN,NaN
1,"RT @LAURAGII: Hoy así ... Multicolor, brillant...",Miguel Almanza,None,None,"Celaya, Guanajuato",es,None,NaN,NaN
2,"@BTS_twt EEE my beautiful flowers. :"")💜 i just...",KawaiiAsagao🐰🌈🌸🌻🌷🍀🍧🌞🦋🌺💫💐🍬🌼🍉❄️,None,None,Kawaiiland (◕‿◕✿) (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧,en,None,NaN,NaN
2,＊新宿エロ垢女子\n\n内容：お昼か夕方冷やかししない人で容姿気にしない人で写メ要求しない人...,東京セフレ募集,None,None,日本 東京,ja,None,NaN,NaN
2,RT @inariya_fusa: ✨冬コミ当選しました～！\n12/29(土) 東地区 シ...,にょ🐾12/29東4 シ69b,None,None,,ja,None,NaN,NaN
2,RT @milodankeju: 🎉 1ST GIVEAWAY 🎉\ngiveaway ke...,Dyo Uchi,None,None,,in,None,NaN,NaN
2,"RT @LAURAGII: Hoy así ... Multicolor, brillant...",Carlos Adrián Torres,None,None,"Xochimilco, Distrito Federal",es,None,NaN,NaN
3,"@bestcryptoexc 🔹 Mighty Signals, Upto 23%-50% ...",Alisha,None,None,"Evansville, Indiana, USA",en,None,NaN,NaN
3,～簡単にちょっとだけ本指名がかえってくる写メ日記～\nお客様とのツーショットの写真\n（顔に...,ましゅまろプロダクション,None,None,,ja,None,NaN,NaN
3,RT @AWA_official: ／\n#高柳明音\nラジオプレイリスト公開！！📣🐥\n＼...,たけちよ,None,None,埼玉 川越市,ja,None,NaN,NaN
3,"Sapa yg tak suka budak kecil, dia gila ...😭 co...",Hanim,None,None,Malaysia,in,None,NaN,NaN
3,"RT @LAURAGII: Hoy así ... Multicolor, brillant...",BetunBetun,None,None,Ciudad de México,es,None,NaN,NaN
4,"@Tomm_Shelby 🔹 Powerful Signals, Upto 23%-50% ...",Laura,None,None,"Bellevue, Washington, USA",en,None,NaN,NaN
4,@vinGbassman ！？！？！？！？\n写メはアプリさまさまです😭\n世の中の女の子も...,りーちゃん,None,None,,ja,None,NaN,NaN
4,"@yuminomi622 @ActorLeeMinHo ゆみちゃんアンニョン*˙︶˙*)ﾉ""...",のんちー🐬,None,None,アクアライン,ja,None,NaN,NaN
4,"RT @Morennars157: Sou cega, muda e surda. Quan...",cg 👑,None,None,"Rocinha, RJ",pt,None,NaN,NaN
4,"RT @LAURAGII: Hoy así ... Multicolor, brillant...",Daniel glez,None,None,"Agua Dulce, Veracruz de Ignaci",es,None,NaN,NaN
5,@CoinTradingBot @AdminXET @PundiXLabs @quoine_...,Debra,None,None,"Newark, New Jersey, USA",en,None,NaN,NaN
5,RT @reiou0106: でも大体の人が毎日頑張ってるよね\nつまり人類みなえら子なんじ...,🥔,None,None,♪♪♪♪♪♪♪♪♪,ja,None,NaN,NaN
5,デザフェス明々後日じゃん🤩鏡の包装どうしよう😂,ちあき@デザフェス48 両日,None,None,大阪→東京,ja,None,NaN,NaN
5,@putrii_1991 @PuspitaFM Pepet terus...jangan k...,Isabel,None,None,"east java, Indonesia",in,None,NaN,NaN
5,"RT @LAURAGII: Hoy así ... Multicolor, brillant...",J Guillermo Cantú #333DELUXE 🇬🇹,None,None,Guatemala,es,None,NaN,NaN
...,...,...,...,...,...,...,...,...,...
1381,@Purify_toast17 I see what you did there. 😂😂,Serena's Catsuit™,None,None,A beach & the border fence,en,None,NaN,NaN
1382,😩😩😂😂🤣RT @Purify_toast17: Porsha looking like R...,Yolanda Marie,None,None,"Atlanta, GA~Nashville, TN",en,None,NaN,NaN
1383,甲賀忍法帖はずるい👏\n久しぶりにやることになりそう,ふります,None,None,,ja,None,NaN,NaN
1384,guys i left tropical😭😭😭😭,#vEx ¿🧞‍♂️🍬,None,None,TF LIVES IN MY HEART❤️,en,None,NaN,NaN
1385,"@feranmi_4aces Loool, I can’t relate to how yo...",Master Lover.,None,None,"Toronto, Ontario",en,None,NaN,NaN
1386,@Wautv_ @SaKe_Vex @IAmTaichou @iamfiend @Zerva...,Altin Memaj,None,None,,en,None,NaN,NaN
1387,@lerdhan @Dha_mist @MademoiselleEne @maggi_nig...,Loci,None,None,Lagos,en,None,NaN,NaN
1388,@jeremycorbyn @Rugby_Labour Dianne Abbot on th...,Common Sense Chap,None,None,,en,None,NaN,NaN
1389,RT @ESPNFantasy: An accurate depiction of fant...,M.A.T.,None,None,STL,en,None,NaN,NaN
1390,@LilNasX This is so accurate 😂😂😂,😴😎,None,None,"Florida, USA",en,None,NaN,NaN
1391,RT @Psychicmix: Honest and Accurate Psychic Re...,Psychic Mix,None,None,,en,None,NaN,NaN
1392,RT @BLACKPINKXTH: 🌸#JENNIE [SOLO] PHOTOBOOK\n\...,RAPPER CHU,None,None,SOSHI X BLACKPINK,vi,None,NaN,NaN
1393,RT @AlmiightyMJ_: You say you fwm but your act...,🌊.,None,None,Zone 6,en,None,NaN,NaN
1394,Clearly Texas is confused about what season it...,Alisha Hayes,None,None,~Headed for Greatness~,en,None,NaN,NaN
1395,RT @pwr_coin: Also waiting for the next bull r...,Dewey,None,None,,en,None,NaN,NaN
1396,RT @markusjayvc: ICON @helloiconworld x @Deblo...,Ace Stojevski,None,None,"Melbourne, Victoria",en,None,NaN,NaN
1397,RT @Maximus_4EVR: #News: Shock &amp; Awe as Re...,Mike Jackson,None,None,,en,None,NaN,NaN
1398,Goodnight I love @intromoonrise more than anyt...,i. 이사벨라 loves alec,None,None,they/them,en,None,NaN,NaN
1399,RT @CoruscaKhaya: See what you've done @MmusiM...,That_Fat_Dude,None,None,"Soweto, South Africa",en,South Africa,-28.816624,24.991639
1400,RT @CoruscaKhaya: See what you've done @MmusiM...,State Capture News,None,None,South Africa,en,South Africa,-28.816624,24.991639
1401,See what you've done @MmusiMaimane 😎😎😎\n\nNext...,Khaya Sithole,None,None,"Johannesburg, South Africa",en,South Africa,-28.816624,24.991639
1402,RT @selinophil: The different between their pe...,P@nni@2503,None,None,,en,None,NaN,NaN
1403,RT @BCMF_FanMeetTH: We gonna throw a PARTY!!!🤩...,Anthra รักเจ๊มากพอๆกับรักจิ๋ว,None,None,เรือยอร์ช freebatch,th,None,NaN,NaN
1404,RT @ronnyravegan: The right: you fucking pussy...,kitty 🌞,None,None,"Gig Harbor, WA",en,None,NaN,NaN
1405,@Juliejamxl Well if you’re gonna throw your ol...,Mutalib1209,None,None,,en,None,NaN,NaN
1406,RT @ronnyravegan: The right: you fucking pussy...,serena 🌿,None,None,"Houston, TX",en,None,NaN,NaN
1407,RT @jz_tamago: 11月5日は #いいたまごの日\nオムレッツくんぬいぐるみ(大...,はなまる,None,None,温室,ja,None,NaN,NaN
1408,Dogs of all sizes and breeds love our pawty bo...,Surprise Pawty,None,None,"Los Angeles, CA",en,None,NaN,NaN
1409,RT @jz_tamago: 11月5日は #いいたまごの日\nオムレッツくんぬいぐるみ(大...,ジェスくん,None,None,日本,ja,None,NaN,NaN
1410,Join Mahdi be a Winner....\nU16 team facing Ba...,GOWFC,None,None,"Isa Town, Bahrain",de,‏البحرين‎,26.155125,50.534461

In [17]:
df_allin['address'].value_counts()

India                                                                    47
USA                                                                      38
Philippines                                                              21
日本                                                                       18
Indonesia                                                                16
South Africa                                                             11
France métropolitaine, France                                            10
Australia                                                                 8
Canada                                                                    7
Georgia, USA                                                              7
Singapore, Central, 178957, Singapore                                     7
Nigeria                                                                   6
ประเทศไทย                                                                 6
Jamaica                                                                   6
Bangladesh, Bhabanipur, ময়মনসিংহ বিভাগ, বাংলাদেশ                         5
ព្រះរាជាណាចក្រ​កម្ពុជា                                                    5
Perú                                                                      5
РФ                                                                        4
Malaysia                                                                  4
‏پاکستان‎                                                                 4
Kenya                                                                     4
香港 Hong Kong, 中西區 Central and Western District, HK, PACIFIC PLACE, 中国     4
Việt Nam                                                                  3
Zimbabwe                                                                  3
Puerto Rico, Orocovis, Puerto Rico, USA                                   3
România                                                                   3
Sénégal                                                                   3
臺灣, 信義鄉, 南投縣, 臺灣省, 臺灣                                                     2
New Zealand/Aotearoa                                                      2
Argentina                                                                 2
Ireland                                                                   2
Colombia                                                                  2
Ghana                                                                     2
Deutschland, Europe                                                       1
Jersey                                                                    1
R.D.                                                                      1
Ecuador                                                                   1
Paraguay                                                                  1
السعودية                                                                  1
Bolivia                                                                   1
Italia                                                                    1
‏البحرين‎                                                                 1
Türkiye                                                                   1
Ciudad de México, Cuauhtémoc, 06060, México                               1
België / Belgique / Belgien                                               1
中国                                                                        1
Name: address, dtype: int64

In [18]:
#This takes forever to run...scrap it

'''
import emoji

india = []

def extract_emoji():
    
    for i, row in df_allin.iterrows():
        for k in df_allin['address']:
            for e in emoji.UNICODE_EMOJI:
                if k == 'India':
                    india.append(e)
            
extract_emoji() 

'''

"\nimport emoji\n\nindia = []\n\ndef extract_emoji():\n    \n    for i, row in df_allin.iterrows():\n        for k in df_allin['address']:\n            for e in emoji.UNICODE_EMOJI:\n                if k == 'India':\n                    india.append(e)\n            \nextract_emoji() \n\n"

In [19]:
jp = df_allin[(df_allin['address'] == '日本')]
jp_allin = pd.DataFrame(jp)
jp_allin

,text,screen_name,latLong,tweetLocation,userLocation,tweetLang,address,latitude,longitude
415,RT @Megumi_Ogata: 【解禁】開催！\n\n緒方恵美Live「禊-2018-」...,涼音（Suzune)＠ADAにハックられ中,None,None,Japan Tokyo,ja,日本,36.574844,139.239418
415,RT @Merozart: #卡拉邦 #キャラスト 就算時間過了還是來發一下（被打飛）路法斯...,桜 雪紀🔥ドワーフのばあちゃん,None,None,Taiwan／↓plz read my TwitterMap,zh,日本,36.574844,139.239418
463,ジュンスお帰りなさい‼️\n\n#기다렸어_준수야\n#Welcome_back_XIA\n...,masako,None,None,Japan,ja,日本,36.574844,139.239418
463,@sasami_3go 青プ23だった😣そうか三連休…！,おすし,None,None,,ja,日本,36.574844,139.239418
471,I made a tent fort with a blanket over her bed...,Meguppe 🇯🇵🐿🌰,None,None,"USA (from Capcom city, Japan)",en,日本,36.574844,139.239418
471,ひゃ〜🙈💗🙈💗🙈💗 https://t.co/VGeHhh0Bru,ＡｉＫＡ,None,None,♨️,ja,日本,36.574844,139.239418
476,@89d6334351a748f # GalaxyGift ～Galaxy Note9 発売...,Galaxy Mobile Japan,None,None,"Tokyo, Japan",ja,日本,36.574844,139.239418
476,@nktrc うひゃ〜かわいい😍ほのぼのギャビン家すこです…900ちゃん、ギャビンを下さいっ...,mako⭕️,None,None,世界のAKIBA,ja,日本,36.574844,139.239418
478,@SplaCell # GalaxyGift ～Galaxy Note9 発売記念キャンペー...,Galaxy Mobile Japan,None,None,"Tokyo, Japan",ja,日本,36.574844,139.239418
478,3告白された回数\n\nひゃ、ひゃっかいくらいかなあ〜〜〜🙄🙄🙄,だいず@第5人格,None,None,,ja,日本,36.574844,139.239418
480,@ka5rii # GalaxyGift ～Galaxy Note9 発売記念キャンペーン ...,Galaxy Mobile Japan,None,None,"Tokyo, Japan",ja,日本,36.574844,139.239418
480,3日も家空けるの怖いな…宇宙チョいい子だけど…やっぱり心配だから1泊2日で帰ろう😅,姉,None,None,日本,ja,日本,36.574844,139.239418
482,@Takedakoraaaa # GalaxyGift ～Galaxy Note9 発売記念...,Galaxy Mobile Japan,None,None,"Tokyo, Japan",ja,日本,36.574844,139.239418
482,@fujiichiho お誕生日おめでとうございます🌷♡\n昔も今も、これからもずっとちほち...,wakana。,None,None,🙅🏻‍♀️❤︎,ja,日本,36.574844,139.239418
484,@kouichi8969 # GalaxyGift ～Galaxy Note9 発売記念キャ...,Galaxy Mobile Japan,None,None,"Tokyo, Japan",ja,日本,36.574844,139.239418
484,今日移動中にゆっくり返してます☺️\nリプくれた方遅くなってごめんね！\nみんなまだくれても...,yuu**,None,None,,ja,日本,36.574844,139.239418
989,お母様お綺麗なお方😍 https://t.co/5kyYVQwsPE,Yumi＆mame,None,None,Japan_Tokyo&Okayama,ja,日本,36.574844,139.239418
1300,RT @GeroldMcPherso1: Boys 🐍🐌🐕\nSnakes and snai...,Harry,None,None,Japan,en,日本,36.574844,139.239418

In [20]:
import collections

jp_names = jp_allin['screen_name']

emoji = re.compile(u'[\U00010000-\U0010ffff]')

final = []

for x in jp_names:
    #japan_screen_name = list(filter(emoji.match, x))
    japan_screen_name = list(filter(emoji.match, x))   
    
    for k in japan_screen_name:
        if len(k) > 0:
            final.append(k)
            #print(final)
            emoji_count = collections.Counter(final)

            print(emoji_count)

Counter({'🔥': 1})
Counter({'🔥': 1, '🇯': 1})
Counter({'🔥': 1, '🇯': 1, '🇵': 1})
Counter({'🔥': 1, '🇯': 1, '🇵': 1, '🐿': 1})
Counter({'🔥': 1, '🇯': 1, '🇵': 1, '🐿': 1, '🌰': 1})

In [21]:
#Does not extract EACH emoji

'''
jp_names = jp_allin['screen_name']

try:  
    # UCS-4
    e = re.compile(u'[\U00010000-\U0010ffff]')
except re.error:  
    # UCS-2
    e = re.compile(u'[\uD800-\uDBFF][\uDC00-\uDFFF]')

emojis_names = []  

for x in jp_names:  
    match  = e.search(x)
    if match:
        #emojis_names.append(match.group())
        emojis_names.append(match.group())
        print(emojis_names)
        
#df_jp_name =  pd.DataFrame(emojis_names,columns=['screen_names'])  
#pd.Series(' '.join(df_jp_name['screen_names']).lower().split()).value_counts()[:100]  

'''

"\njp_names = jp_allin['screen_name']\n\ntry:  \n    # UCS-4\n    e = re.compile(u'[𐀀-\U0010ffff]')\nexcept re.error:  \n    # UCS-2\n    e = re.compile(u'[\ud800-\udbff][\udc00-\udfff]')\n\nemojis_names = []  \n\nfor x in jp_names:  \n    match  = e.search(x)\n    if match:\n        #emojis_names.append(match.group())\n        emojis_names.append(match.group())\n        print(emojis_names)\n        \n#df_jp_name =  pd.DataFrame(emojis_names,columns=['screen_names'])  \n#pd.Series(' '.join(df_jp_name['screen_names']).lower().split()).value_counts()[:100]  \n\n"

In [22]:
US = df_all['screen_name'][df_all['userLocation'] == 'United States']
df_us = pd.DataFrame(US)
df_us

                                          screen_name
23                                               🍯KIM
96                            🇺🇸🇺🇸 Bill Melino 💯 🇺🇸🇺🇸
98                                              Ringo
158  Michele#ResistorSister#VetsResistSupportSquadron
237                                            Tumblr
295                                  Bougiee Eriica💕✨
371                                       Steve Yerrr
502                                 Vote November 6th
530                                              Lumi
654                                    MONO💜Playlist💜
659                                            Meg 🇺🇸
662                                         KingNiall
732                                            Yozora
863                                  R.I.P Chris Cole
883                                              Cami
30                                   愛慕依🐜✊✊✊Guo.Media
54                        🇺🇸Ryo's English🇺🇸@英語&USA写真垢
214                                              握拳而立

In [23]:

US_names = df_us['screen_name']

try:  
    # UCS-4
    e = re.compile(u'[\U00010000-\U0010ffff]')
except re.error:  
    # UCS-2
    e = re.compile(u'[\uD800-\uDBFF][\uDC00-\uDFFF]')

emojis_names = []  

for x in US_names:  
    match  = e.search(x)
    if match:
        emojis_names.append(match.group())

df_us_name =  pd.DataFrame(emojis_names,columns=['screen_names'])  
pd.Series(' '.join(df_us_name['screen_names']).lower().split()).value_counts()[:100]

🇺    3
💜    1
🐜    1
🍯    1
💕    1
dtype: int64

In [24]:
#Emojis used in screen_names where userLocation = symbols


jp_names = df_jp['screen_name']

try:  
    # UCS-4
    e = re.compile(u'[\U00010000-\U0010ffff]')
except re.error:  
    # UCS-2
    e = re.compile(u'[\uD800-\uDBFF][\uDC00-\uDFFF]')

emojis_names = []  

for x in jp_names:  
    match  = e.search(x)
    if match:
        emojis_names.append(match.group())

df_jp_name =  pd.DataFrame(emojis_names,columns=['screen_names'])  
pd.Series(' '.join(df_jp_name['screen_names']).lower().split()).value_counts()[:100]

💜    6
🐰    5
🌸    5
🍓    5
🐻    4
🐶    4
🐼    4
🌟    3
🐧    3
🌈    3
🌷    2
💪    2
🌱    2
🦇    2
🐈    2
🐱    2
😸    2
💙    2
🍒    2
🍑    2
👑    2
🐾    2
🍀    2
🎀    1
🐢    1
🙅    1
🎉    1
🍆    1
🐠    1
🥟    1
    ..
🐒    1
🌹    1
🙌    1
🍇    1
🦊    1
💃    1
🥇    1
😼    1
🦐    1
🦋    1
💋    1
💕    1
😇    1
🐣    1
🐏    1
𖤐    1
🍰    1
🤡    1
💖    1
𝓜    1
🌵    1
🔥    1
🚕    1
🚶    1
🚸    1
🍄    1
🐬    1
🎈    1
🕊    1
🗼    1
Length: 90, dtype: int64

In [25]:
name_en = df_all['screen_name'][df_all['tweetLang'] == 'en']
df_en = pd.DataFrame(name_en)
df_en

                        screen_name
1                      Scorpioo ♏️💧
2     KawaiiAsagao🐰🌈🌸🌻🌷🍀🍧🌞🦋🌺💫💐🍬🌼🍉❄️
3                            Alisha
4                             Laura
5                             Debra
6                             Carla
7                             Kerry
8                           Shelley
9                        Princesita
10                      Et'z_Deuces
12                      Et'z_Deuces
13                      Et'z_Deuces
14                      Et'z_Deuces
15                      Et'z_Deuces
16                            peach
17                          rhys 11
18             CARL THEWOODBRUSSELS
19                     Brian Becker
20                             Gail
21                               🇹🇹
22                 🦃 lil thankful 🦃
23                             🍯KIM
24                        JustLyns!
25                             8495
26                    Nessa Spencer
27                     Alaro Victor
28                     Laurie Allan
29               Ted Clubberlang. ❌
30                            nico.
31                            robin
...                             ...
1394                   Alisha Hayes
1395                          Dewey
1396                  Ace Stojevski
1397                   Mike Jackson
1398             i. 이사벨라 loves alec
1399                  That_Fat_Dude
1400             State Capture News
1401                  Khaya Sithole
1402                     P@nni@2503
1404                        kitty 🌞
1405                    Mutalib1209
1406                       serena 🌿
1408                 Surprise Pawty
27                       ZACK AMINU
39                            wangs
42                       😁Minhoon4😊
65                 LoveDarlingPabsu
80                             Mel👑
113              sneh08(FQ_is_Love)
137                   Ahmed Hasaan™
138                 Durag Jones  🎙😩
139        ツI❤️ℳamaCindy&MYIDOLSツ 💖
180                               ✨
15              Michael Meezy Davis
18                       Michael G.
19                              Pam
99                            shawn
103                  Michael Rocker
134                     good vibes.
154                 Cateto Chiquito

[1097 rows x 1 columns]

In [26]:
#Emojis used in screen_names where tweetLang == eng

emo_names = df_en['screen_name']

try:  
    # UCS-4
    e = re.compile(u'[\U00010000-\U0010ffff]')
except re.error:  
    # UCS-2
    e = re.compile(u'[\uD800-\uDBFF][\uDC00-\uDFFF]')

emojis_names = []  

for x in emo_names:  
    match  = e.search(x)
    if match:
        emojis_names.append(match.group())

dfe1 =  pd.DataFrame(emojis_names,columns=['screen_names'])  
pd.Series(' '.join(dfe1['screen_names']).lower().split()).value_counts()[:100]

👑    12
💜    10
🖤     8
💙     7
💖     7
🦋     6
💋     6
🍭     6
🥀     5
🇺     5
🍂     5
🐝     5
🏳     4
🌹     4
🎃     4
💎     4
🌺     4
🇲     4
💕     3
🔥     3
🌻     3
🌸     3
🥰     3
🌟     3
🇮     3
🌙     3
🍯     3
🤴     2
🆗     2
🌊     2
     ..
𝓑     1
😝     1
🌿     1
😔     1
😜     1
🤫     1
💦     1
🅰     1
🎸     1
🃏     1
🐦     1
😋     1
🎙     1
📠     1
🐼     1
🍺     1
🍄     1
💟     1
🍍     1
💭     1
𝕁     1
🤔     1
🐷     1
🦖     1
🐧     1
💅     1
𝐟     1
🌪     1
🤯     1
🎯     1
Length: 100, dtype: int64

In [27]:
#Clean up tweet text data; assign to variable tweets to be used in loop below

tweets = df_all['text'].drop_duplicates().values.tolist()

tweets  = [x for x in tweets if not x.startswith('RT')]

tweets = [i for i in tweets if not ('http://' in i or 'https://' in i)]

In [28]:
#This shows most used emojis in tweet text

try:  
    # UCS-4
    e = re.compile(u'[\U00010000-\U0010ffff]')
except re.error:  
    # UCS-2
    e = re.compile(u'[\uD800-\uDBFF][\uDC00-\uDFFF]')

emojis = []  
for x in tweets:  
    match  = e.search(x)
    if match:
        emojis.append(match.group())

dfe =  pd.DataFrame(emojis,columns=['text'])  
pd.Series(' '.join(dfe['text']).lower().split()).value_counts()[:100]

😂    92
😭    52
😍    21
🤣    20
🤔    19
😊    15
🙏    14
😘    14
😇    12
💕    12
👍    11
😅    11
😌    10
🤦    10
🤤     9
🎶     9
😆     8
😳     8
👏     7
😔     7
🤧     7
🙄     7
💦     7
😩     7
😢     6
🔥     6
🎵     6
💖     6
🙃     6
😁     6
     ..
💧     2
👉     2
🤞     2
🐾     2
🤨     2
💯     2
😑     2
💁     2
😗     2
🌸     2
🖐     2
💛     2
😜     2
🥰     2
🌚     2
🐈     2
🌻     2
💞     2
🦀     2
🤯     2
😨     2
🎉     2
💢     2
😯     2
👯     1
💭     1
😶     1
🌟     1
🦇     1
💩     1
Length: 100, dtype: int64

In [29]:
#This shows most used emojis in screen names

emo_names_all = df['screen_name']

try:  
    # UCS-4
    e = re.compile(u'[\U00010000-\U0010ffff]')
except re.error:  
    # UCS-2
    e = re.compile(u'[\uD800-\uDBFF][\uDC00-\uDFFF]')

emojis_names = []  

for x in emo_names_all:  
    match  = e.search(x)
    if match:
        emojis_names.append(match.group())

dfe1 =  pd.DataFrame(emojis_names,columns=['screen_names'])  
pd.Series(' '.join(dfe1['screen_names']).lower().split()).value_counts()[:100]

NameError: name 'df' is not defined

In [ ]:
from geopy.geocoders import Nominatim
from geotext import GeoText
from geopy.extra.rate_limiter import RateLimiter

#data = []
#with open('result/good_tweets.json') as f:
#    for line in f:
#        data.append(json.loads(line))     

geolocator = Nominatim(country_bias="United States")

geocode = RateLimiter(geolocator.geocode, min_delay_seconds=5)

for i,j in enumerate(df_all):
    places = GeoText(j['user']['location'])
#     if places.cities:
    if places.countries:
        location = geolocator.geocode(places.countries[0], exactly_one=True)
        try:
            address = location.address
            latitude = location.latitude
            longitude = location.longitude
            print("index in good_tweets.json = {}, place name = {}, latitude = {}, longitude = {}:".format(i, address, latitude, longitude))
        except AttributeError:
            print("Error, {} not found".format(str(places.cities)))